### ISSUE TITLE
fix integration with schedulemaker

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCS/coursedescriptions#29]
https://github.com/briangathright/comp-schedulemaker

Right now, the output of the schedulemaker script has to be manually copied into this repo. This is tedious and error-prone. 

Instead, it will probably be best to handle the generated schedule completely outside this Sphinx site by, say, linking there directly from T4.

**Comment by gkthiruvathukal** [comment]
Agreed with @klaeufer here. Sorry it took so long to act upon this issue. I convened a meeting of web site folks today--yes, almost 2.5 years after you reported it--and we decided to give this script one more semester to live. The script is going to live in a new repo. We'll use it to generate schedules. If it stops working, we are probably going to default to LOCUS for all schedule information going forward.

**Comment by gkthiruvathukal** [comment]
The new repo for the script will be https://github.com/LoyolaChicagoCS/csv2schedule.
