### ISSUE TITLE
update encrypted credentials for Travis script

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCS/coursedescriptions#69]
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/LoyolaChicagoCS/coursedescriptions.git/'
The command "GH_USER=LoyolaChicagoCS GH_REPO=coursedescriptions "./gh-pages.sh"" exited with 128.

**Comment by gkthiruvathukal** [comment]
I took care of this by provisioning new tokens.
